// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_hidden/[username].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/random-uuid.ts";
import * as $3 from "./routes/countdown.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/search.tsx";
import * as $$0 from "./islands/Countdown.tsx";

const manifest = {
  routes: {
    "./routes/_hidden/[username].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/random-uuid.ts": $2,
    "./routes/countdown.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/search.tsx": $5,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
