# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

# **What it does**: Builds the static site and deploy to GitHub pages.
# **Why we have it**:
#   To avoid having to manually build and push the site every time.
# **Who does it impact**: The GitHub pages site.

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: pnpm

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ secrets.CACHE_RANDOM_STRING }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ secrets.CACHE_RANDOM_STRING }}-${{ hashFiles('**.svelte', '**.[tj]sx?') }}

      - name: Build site
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload site directory.
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
